from __future__ import annotations

from typing import Protocol


class SnifferProtocol(Protocol):
    def start_capture(self, interface: str) -> None: ...
    def stop_capture(self) -> None: ...
    def save_capture_as_flow(self, flow_filepath: str) -> None: ...
